name: QC Checks

on:
  push:
    branches-ignore:
      - stable
      - beta
    tags-ignore:
      - "**"

jobs:
  checks:
    name: QC Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm install

      - name: ESLint checks
        run: npm run eslint-check

      - name: Stylelint checks
        run: npm run stylelint-check

      - name: Prettier checks
        run: npm run prettier-check

      - name: TSC checks
        run: npm run tsc-check

  tests:
    name: Tests Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Run tests
        env:
          NODE_OPTIONS: --loader=ts-node/esm
          TS_NODE_PROJECT: server/tsconfig.json
        run: npx mocha --config server/.mocharc.json

      - name: Client build checks
        run: npm run build-client

      - name: Server build checks
        run: npm run build-server
